# Generated by Django 5.1.4 on 2024-12-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='tags',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='tags',
            field=models.ManyToManyField(related_name='job_posts', to='portal.tag'),
        ),
    ]
