# Generated by Django 5.1.4 on 2024-12-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_tag_remove_jobpost_tags_jobpost_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='tags',
            field=models.CharField(default='c', max_length=50),
            preserve_default=False,
        ),
    ]
